// @api-version 1.0

const config = requestFromUser("Midjourney Aesthetic Prompt", "Enhance", function () {
  return [
    this.textField("Ocean of beer cans", "Enter your base prompt", true, 100),
    this.switch(true, "Add Artist"),
    this.switch(true, "Add Photographer"),
    this.switch(true, "Add Style"),
    this.switch(true, "Add Shading"),
    this.switch(false, "Add Camera"),
    this.switch(false, "Add Lens"),
    this.switch(true, "Add Lighting"),
    this.switch(true, "Enhance Quality"),
    this.switch(true, "Add Video Game Style"),
    this.switch(true, "Add Director Style")
  ];
});

const artists = [
"Greg Rutkowski", "Artgerm", "Alphonse Mucha", "Studio Ghibli", "Hayao Miyazaki",
  "Beeple", "Simon Stålenhag", "Moebius", "James Jean", "Alex Ross",
  "Syd Mead", "Katsuhiro Otomo", "Magali Villeneuve", "H.R. Giger", "Ashley Wood",
  "WLOP",
  "Feng Zhu",
  "Loish",
  "Craig Davison",
  "Alena Aenami",
  "Yoshitaka Amano",
  "Kim Jung Gi",
  "Ilya Kuvshinov",
  "Ross Tran",
  "Marco Nelor",
  "Sergey Kolesov",
  "Sam Spratt",
  "Peter Mohrbacher",
  "Ruan Jia",
  "Shunya Yamashita",
  "Dan Luvisi",
  "Karla Ortiz",
  "Aaron Griffin",
  "David Álvarez",
  "Tyler Edlin",
  "Bastien Lecouffe-Deharme",
  "Izaksm",
  "Goro Fujita",
  "Paul Chadeisson",
  "Even Mehl Amundsen",
  "Kazuki Takahashi",
  "Ralph McQuarrie",
  "Brian Froud",
  "John Blanche",
  "Tom Bagshaw",
  "Gustave Doré",
  "Peter de Sève",
  "Wayne Barlowe",
  "Frank Frazetta",
  "Jean Giraud",
  "Alex Grey",
  "Karla Ortiz",
  "Jeremy Mann",
  "Yoji Shinkawa",
  "Hajime Sorayama",
  "Brom",
  "Michael Whelan",
  "Donato Giancola",
  "Pascal Blanche",
  "Michael Kutsche",
  "Zdzisław Beksiński",
  "Jason Chan",
  "Jesper Ejsing",
  "Tim Bradstreet",
  "Jacek Yerka",
  "Yoshitaka Amano",
  "Ken Sugimori",
  "Hidetaka Miyazaki",
  "Takeshi Honda",
  "Katsuya Terada",
  "Tsutomu Nihei",
  "Kazuo Oga",
  "Toshihiro Kawamoto",
  "Mamoru Nagano",
  "Yoji Shinkawa",
  "Kekai Kotaki",
  "Bengus",
  "Akihiko Yoshida",
  "Tetsuya Nomura",
  "Yusuke Kozaki",
  "Shigenori Soejima",
  "Masashi Kishimoto",
  "Eiichiro Oda",
  "Hiro Mashima",
  "Naoko Takeuchi",
  "Tite Kubo",
  "Leiji Matsumoto",
  "Hajime Isayama",
  "CLAMP",
  "Kaoru Mori",
  "Simon Dominic",
  "Daniel Lieske",
  "David Revoy",
  "Jeremy Geddes",
  "Jama Jurabaev",
  "Greg Tocchini",
  "Nicolas Delort",
  "Tran Nguyen",
  "Jakub Rozalski",
  "Marija Tiurina",
  "Teagan White",
  "Kelly McKernan",
  "Yukai Du",
  "Kilian Eng",
  "Victo Ngai",
  "Eyvind Earle",
  "Matt Rhodes",
  "Milan Nikolic",
  "Ian McQue",
  "Dorian Vallejo",
  "Tiffany Turrill",
  "Armand Serrano",
  "Ryan Lang",
  "Andy Park",
  "Glen Keane",
  "Rovina Cai",
  "James Gurney",
  "Tom Lovell",
  "Zoltan Boros",
  "Gabor Szikszai",
  "Allen Williams",
  "Don Maitz",
  "Peter Mohrbacher",
  "Victor Mosquera",
  "Jakub Rebelka",
  "Ian Sprigger",
  "Kekai Kotaki",
  "Wei Feng",
  "Yoshitaka Amano",
  "Dave Rapoza",
  "Sergey Kolesov",
  "Miles Johnston",
  "Gustave Klimt",
  "John Harris",
  "Jared Muralt",
  "Camille Kuo",
  "Hikari Shimoda",
  "David Hockney",
  "Ron English",
  "Chiho Aoshima"
];

const photographers = [
"Ansel Adams", "Annie Leibovitz", "Gregory Crewdson", "Helmut Newton",
  "Richard Avedon", "Steve McCurry", "Sebastião Salgado", "Ellen von Unwerth",
  "Brandon Woelfel",
  "Peter McKinnon",
  "Henri Cartier-Bresson",
  "Fan Ho",
  "Dorothea Lange",
  "David LaChapelle",
  "Jimmy Chin",
  "Chris Burkard",
  "Mario Testino",
  "Cindy Sherman",
  "Sebastiao Salgado",
  "Bill Brandt",
  "Nan Goldin",
  "Saul Leiter",
  "Vivian Maier",
  "Diane Arbus",
  "Man Ray",
  "Robert Mapplethorpe",
  "Guy Bourdin",
  "Bruce Gilden",
  "Irving Penn",
  "Herb Ritts",
  "Horst P. Horst",
  "David Bailey",
  "Lee Friedlander",
  "Robert Frank",
  "William Eggleston",
  "Arnold Newman",
  "Philippe Halsman",
  "Imogen Cunningham",
  "Nick Knight",
  "Garry Winogrand",
  "Mary Ellen Mark",
  "Larry Sultan",
  "Todd Hido",
  "Alex Prager",
  "Zanele Muholi",
  "Elliott Erwitt",
  "Taryn Simon",
  "Jill Greenberg",
  "Helene Binet",
  "Andreas Gursky",
  "Martin Parr",
  "Michael Kenna",
  "Candida Höfer",
  "Wolfgang Tillmans",
  "Thomas Struth",
  "Nadav Kander",
  "Dan Winters",
  "Paolo Roversi"
];

const styles = [
"Oil painting", "Watercolor", "Photorealistic", "Concept art",
  "Synthwave", "Cyberpunk", "Steampunk", "Pixel art", "Ink sketch",
  "Fantasy realism", "Digital matte painting", "Baroque",
  "Neo-noir",
  "Modern minimalism",
  "Low-poly",
  "Futurism",
  "Vaporwave",
  "Biopunk",
  "Art Brut",
  "Neo-futurism",
  "Brutalism",
  "Maximalism",
  "Digital surrealism",
  "Abstract expressionism",
  "Gothic revival",
  "New Romanticism",
  "Hypermodernism",
  "Afrofuturism",
  "Dark academia",
  "Cottagecore",
  "Post-apocalyptic",
  "Noir",
  "New media art",
  "Surreal minimalism",
  "Abstract neon",
  "Expressionist realism",
  "AI-collage",
  "Digital baroque",
  "Cyber deco",
  "Speculative design",
  "Visual kei",
  "Trompe-l'œil",
  "Retro sci-fi",
  "Neo-expressionism",
  "Industrial surrealism",
  "Analog horror",
  "Procedural art",
  "Neon pop art",
  "Augmented reality aesthetic",
  "Modern cubism",
  "Mythological expressionism",
  "Isometric vector",
  "Techno romanticism",
  "Hyper-surrealism",
  "AI generative minimalism",
  "Virtual fashion design",
  "Crystalline architecture",
  "Fantasy watercolor",
  "Brutalist horror",
  "Conceptual architecture",
  "Cyber magical realism",
  "Narrative surrealism",
  "Architectural maximalism",
  "Impressionist futurism",
  "Kinetic sculpture aesthetic",
  "AI glitch art",
  "Celestial realism",
  "Deep dream look",
  "Non-Euclidean geometry style",
  "Digital collage",
  "Atmospheric matte",
  "Hypervector anime",
  "Pop surrealism",
  "Magical realism",
  "Post-cyberpunk",
  "Retro futurism",
  "Dystopian deco",
  "Cinematic illustration",
  "Neo-gothic digital",
  "VHS horror",
  "Holographic aesthetic",
  "Neo-impressionism",
  "Fashion sketch style",
  "Dynamic graffiti",
  "Pastel goth",
  "Sci-fi ukiyo-e",
  "Lowbrow painting"
];

const shadings = [
"Cel shading", "Ambient occlusion", "Cross hatching", "Soft shadows", "Rim shading", "Dramatic chiaroscuro",
  "Subsurface scattering",
  "Raytraced shadows",
  "Gradient ramp shading",
  "Hard edge toon shading",
  "Sculptural light modeling",
  "Core shadow emphasis",
  "Procedural shading",
  "Light scattering passes",
  "Reflective surface bounce",
  "Shadow ramping",
  "Digital impasto",
  "Occlusion-only sketch",
  "High-fidelity AO",
  "Painterly toon blend",
  "Specular highlight trace",
  "Halftone overlay",
  "Subtle grain matte",
  "Chromatic edge shade",
  "Comic ink layer",
  "Fresnel rim falloff",
  "Volumetric ink shading",
  "Gradient stipple blend",
  "Neon edge highlights",
  "Luminance contouring",
  "Anime diffusion haze"
];

const cameras = [
"Canon EOS 5D Mark IV", "Hasselblad X1D", "Sony Alpha 7R IV",
  "Fujifilm GFX 100", "Nikon Z9", "Panasonic Lumix GH6",
  "Leica M10",
  "Canon R5",
  "RED Komodo 6K",
  "Sony FX3",
  "Arri Alexa Mini",
  "Blackmagic Pocket 6K",
  "DJI Zenmuse X7",
  "Nikon D850",
  "Canon 1DX Mark III",
  "Panavision DXL2",
  "Sony A7S III",
  "Canon C300 Mark III",
  "Blackmagic URSA Mini",
  "RED Epic-W",
  "GoPro Hero12",
  "DJI Pocket 2",
  "Canon EOS R3",
  "Leica SL2",
  "Phase One XT",
  "Z CAM E2-F6",
  "Canon EOS R6",
  "Sony A1",
  "RED V-Raptor",
  "Nikon Z8",
  "DJI Inspire 3",
  "Panasonic S1H",
  "Fujifilm X-H2S",
  "Leica Q2",
  "Canon XF605",
  "Sony ZV-E1",
  "Canon EOS R50",
  "Sony FX6",
  "RED Scarlet-W",
  "GoPro Max",
  "Blackmagic Cinema Camera 4K",
  "Fujifilm X-T5",
  "DJI Ronin 4D",
  "Canon XA75",
  "Panasonic BGH1",
  "Nikon Z fc",
  "Canon EOS C70",
  "Blackmagic URSA Broadcast G2",
  "Sony A9 III",
  "Fujifilm GFX100 II",
  "RED Ranger Helium 8K",
  "DJI Air 3",
  "Z CAM E2-F8",
  "Canon Vixia HF G70",
  "Nikon Z30",
  "Leica M11"
];

const lenses = [
"50mm f/1.4", "85mm f/1.2", "16-35mm f/2.8", "24-70mm f/2.8",
  "100mm macro", "70-200mm f/2.8", "35mm f/1.8",
  "14mm ultra wide",
  "24mm tilt-shift",
  "200mm telephoto",
  "10-18mm wide zoom",
  "Fisheye 8mm",
  "300mm f/4 prime",
  "Sigma Art 35mm f/1.4",
  "Canon RF 28-70mm f/2L",
  "Zeiss Otus 55mm f/1.4",
  "Laowa 24mm Probe",
  "Tamron 35-150mm f/2-2.8",
  "Canon RF 100mm f/2.8",
  "Tokina 11-16mm f/2.8",
  "Zeiss 135mm f/2",
  "Sigma 105mm f/1.4",
  "Canon 600mm f/4L",
  "Laowa 15mm f/4 wide macro",
  "Meike 85mm T2.2 cine",
  "Samyang 14mm f/2.8",
  "Nikon 58mm f/0.95 Noct",
  "Canon RF 85mm f/1.2L",
  "Sony G Master 24mm f/1.4",
  "Sigma 14-24mm f/2.8",
  "Fujinon MK18-55mm",
  "Canon RF 600mm f/11",
  "TTArtisan 50mm f/0.95",
  "Venus Optics 9mm f/5.6",
  "Meike 16mm T2.2",
  "Zeiss 21mm f/2.8",
  "Voigtländer 40mm f/1.2",
  "Canon RF 28mm f/2.8",
  "Samyang 35mm f/1.4",
  "Sigma 85mm f/1.4",
  "Laowa 12mm f/2.8 Zero-D",
  "Mitakon 135mm f/1.4",
  "Voigtlander 10.5mm f/0.95",
  "Meike 50mm T2.2 cine",
  "Canon TS-E 90mm f/2.8",
  "Sigma 18-50mm f/2.8",
  "Fujinon 90mm f/2",
  "Canon RF 10-20mm f/4",
  "Sony FE 135mm f/1.8",
  "Sigma 28-70mm f/2.8",
  "Canon EF 180mm macro",
  "Fujinon XF 23mm f/1.4",
  "Laowa Argus 25mm f/0.95",
  "Panasonic Lumix S Pro 70-200mm",
  "Venus Optics 15mm f/4 Wide Macro",
  "Zeiss Milvus 21mm f/2.8",
  "Meike 35mm T2.1 cine"
];

const lighting = [
"Volumetric lighting", "Cinematic lighting", "Golden hour", "Backlighting",
  "Rim lighting", "Strobe lighting", "Natural diffuse light", "Neon lighting",
  "Studio three-point lighting",
  "Hard light with deep shadows",
  "Overcast daylight",
  "Specular highlights",
  "Low key lighting",
  "Practical lighting",
  "Mixed temperature lighting",
  "Film noir shadows",
  "Neon backglow",
  "Lantern ambient lighting",
  "Chiaroscuro",
  "Stage spotlighting",
  "Rain-diffused lighting",
  "High contrast shadowplay",
  "UV blacklight",
  "Urban twilight glow",
  "Color gels on background",
  "Hard daylight shadow",
  "Flickering TV light",
  "Lightning strike flash",
  "Halogen warm glow",
  "Bioluminescent shimmer",
  "Firefly scatter light",
  "Stage beam highlights",
  "Moonlight reflections",
  "Underwater caustics",
  "Aurora glow",
  "Heatwave distortion",
  "Mirror-bounce light",
  "Flickering fluorescent ambiance",
  "Colored shadowplay",
  "Torchlight contrast",
  "Solar flare highlight",
  "Firelight ambient",
  "Spotlight bloom",
  "Backlight silhouette",
  "Bokeh lens flare",
  "Golden sparkle",
  "Window-cast beam",
  "RGB rim separation",
  "Glowing biotic light",
  "Starlight shimmer",
  "Candlelight softness",
  "LED pulse",
  "Sunset shadow stretch",
  "Reflected desert sun",
  "Lava ambient glow",
  "Overcast noir",
  "Holographic scatter",
  "Surreal moonbeam"
];

const quality = [
"8k", "High resolution", "Detailed", "Intricate",
  "Octane render quality",
  "Photolab grade",
  "RAW photo look",
  "Color depth richness",
  "High poly detail",
  "Physically-based rendering",
  "Color-graded finish",
  "Super-sampled sharpness",
  "AI upscaled",
  "Motion blur realism",
  "VFX-grade detail",
  "Fine-grain sharpness",
  "Ultra-high realism",
  "IMAX resolution",
  "LUT color refinement",
  "Denoised clarity",
  "Pixel-perfect upscaling",
  "Pro photo polish",
  "Depth mapped detail",
  "HDR cinematic finish",
  "Photographic tone mapping",
  "Noise-free depth",
  "Refined grain structure",
  "Deep HDR shadows",
  "Post-production film finish"
];

const anime_artists = [
  "Makoto Shinkai", "Sushio", "Takeshi Koike", "Yoh Yoshinari", "Hidetaka Tenjin",
  "CLAMP", "Mamoru Hosoda", "Hiroyuki Imaishi", "Kazuma Kaneko", "Takeshi Obata",
  "Shingo Yamashita", "Naoko Yamada", "Yutaka Nakamura", "Atsushi Nishigori", "Kenichi Yoshida",
  "Yoshiyuki Tomino", "Hiroyuki Okiura", "Shinichiro Watanabe", "Ryōsuke Takahashi", "Yasuhiro Yoshiura",
  "Masashi Kudo", "Kazuto Nakazawa", "Hidetaka Tenjin", "Yoshinori Kanada", "Satoshi Kon"
];

const movie_directors = [
  "Christopher Nolan", "Ridley Scott", "Denis Villeneuve", "Wes Anderson", "Zack Snyder",
  "Guillermo del Toro", "Terry Gilliam", "Bong Joon-ho", "David Lynch", "Hayao Miyazaki",
  "Akira Kurosawa", "Stanley Kubrick", "Jean-Pierre Jeunet", "Robert Rodriguez", "Luc Besson",
  "Michel Gondry", "James Cameron", "Gore Verbinski", "Neill Blomkamp", "Spike Jonze",
  "Andrei Tarkovsky", "Park Chan-wook", "David Fincher", "Ang Lee", "Robert Eggers"
];

const video_games = [
  "The Last of Us", "Death Stranding", "Control", "Cyberpunk 2077", "Elden Ring",
  "Horizon Zero Dawn", "Bloodborne", "Persona 5", "NieR:Automata", "Journey",
  "Bayonetta", "Jet Set Radio", "Hyper Light Drifter", "Abzû", "Cuphead",
  "Kena: Bridge of Spirits", "Ori and the Blind Forest", "Hades", "Valheim", "Tunic",
  "Gris", "Katana ZERO", "Little Nightmares", "Bastion", "Dead Cells",
  "Return of the Obra Dinn", "Dishonored", "The Witness", "Fez", "Slay the Spire",
  "Blasphemous", "Dredge", "Scorn", "Sable", "Rain World",
  "Paper Mario", "Journey to the Savage Planet", "Solar Ash", "A Short Hike", "Oxenfree"
];

function getRandom(array) {
  return array[Math.floor(Math.random() * array.length)];
}

const basePrompt = config[0];
let finalPrompt = basePrompt;

if (config[1]) finalPrompt += `, by ${getRandom(artists)}`;
if (config[2]) finalPrompt += `, like a photo by ${getRandom(photographers)}`;
if (config[3]) finalPrompt += `, in the style of ${getRandom(styles)}`;
if (config[4]) finalPrompt += `, with ${getRandom(shadings)}`;
if (config[5]) finalPrompt += `, shot on a ${getRandom(cameras)}`;
if (config[6]) finalPrompt += `, with a ${getRandom(lenses)}`;
if (config[7]) finalPrompt += `, with ${getRandom(lighting)}`;
if (config[8]) finalPrompt += `, ${quality.join(", ")}`;
if (config[9]) finalPrompt += `, in the style of ${getRandom(video_games)}`;
if (config[10]) finalPrompt += `, directed by ${getRandom(movie_directors)}`;

requestFromUser("Enhanced Prompt", "Done", function () {
  return [
    this.section("Result", "Copy your enhanced prompt below", [
      this.textField(finalPrompt, "Tap and hold to copy", true, 5)
    ])
  ];
});

params = {
  prompt: finalPrompt
};